# Generated by Django 4.1.5 on 2023-02-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_category_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uodated_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
